apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-py-app
spec:
  selector:
    matchLabels:
      app: hello-py-app
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-py-app
    spec:
      containers:
      - name: hello-py-app
        image: phx.ocir.io/idch4uyl2yza/ce-jcc/hello-py-app:v1
        imagePullPolicy: Always
        ports:
        - name: hello-py-app
          containerPort: 5000
          protocol: TCP
      nodeSelector:
        name: pool1
      imagePullSecrets:
         - name: my-ocirsecret