apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-py
spec:
  selector:
    matchLabels:
      app: helloapp-py
  replicas: 3
  template:
    metadata:
      labels:
        app: helloapp-py
    spec:
      containers:
      - name: helloapp-py
        image: phx.ocir.io/idi1o0a010nx/project01/helloapp-py:v1
        imagePullPolicy: Always
        ports:
        - name: helloapp-py
          containerPort: 5000
          protocol: TCP
#      nodeSelector:
#        name: pool1
      imagePullSecrets:
         - name: my-ocirsecret